name: stp_gnn
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiobotocore==2.25.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - anndata==0.11.4
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - array-api-compat==1.12.0
      - arrow==1.4.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - botocore==1.40.61
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - dask==2024.11.2
      - dask-expr==1.1.19
      - dask-image==2024.5.3
      - datashader==0.18.2
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docrep==0.3.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - geopandas==1.1.1
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - idna==3.11
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - inflect==7.5.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - legacy-api-wrap==1.4.1
      - llvmlite==0.45.1
      - locket==1.0.0
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - matplotlib-scalebar==0.9.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multipledispatch==1.0.0
      - multiscale-spatial-image==2.0.3
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numcodecs==0.13.1
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - ome-zarr==0.11.1
      - omnipath==1.0.12
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - param==2.2.1
      - parso==0.8.5
      - partd==1.4.2
      - patsy==1.0.2
      - pexpect==4.9.0
      - pillow==11.3.0
      - pims==0.7
      - platformdirs==4.5.0
      - pooch==1.8.2
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pycparser==2.23
      - pyct==0.6.0
      - pyg-lib==0.4.0+pt25cu121
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyogrio==0.11.1
      - pyparsing==3.2.5
      - pyproj==3.7.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - s3fs==2025.9.0
      - safetensors==0.7.0
      - scanpy==1.11.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - session-info2==0.2.3
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - slicerator==1.1.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - spatial-image==1.2.3
      - spatialdata==0.5.0
      - squidpy==1.6.5
      - stack-data==0.6.3
      - statsmodels==0.14.5
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.7
      - tinycss2==1.4.0
      - tomli==2.3.0
      - toolz==1.1.0
      - torch==2.5.1+cu121
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt25cu121
      - torch-sparse==0.6.18+pt25cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.1.0
      - typeguard==4.4.4
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - validators==0.35.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - xarray==2025.6.1
      - xarray-dataclass==3.0.0
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zarr==2.18.3
      - zipp==3.23.0